name: NulvoraFriends
version: '1.1.0-SNAPSHOT'
main: com.nulvora.friends.paper.NulvoraFriendsPaper
description: Sistema de amigos para la network Nulvora - Plugin backend
api-version: '1.21'

metadata:
  authors: [Nulvora]

softdepend:
  - PlaceholderAPI

commands:
  amigos:
    description: Ver tu lista de amigos
    aliases: [friends, f, amigo]
    usage: /amigos
    permission: nulfriends.use

permissions:
  nulfriends.use:
    description: Permite usar comandos de amigos
    default: true

config-version: 1
