name: NulvoraFriends
version: '1.2.0-SNAPSHOT'
main: com.nulvora.friends.paper.NulvoraFriendsPaper
api-version: '1.21'
description: Sistema de amigos para la network Nulvora - Plugin backend
authors: [Nulvora]
softdepend: [PlaceholderAPI]
loadbefore: [PlaceholderAPI]

commands:
  amigos:
    description: Ver tu lista de amigos
    aliases: [friends, f, amigo]
    usage: /amigos

channels:
  nulfriends:
    version: 1
